version: '3'

services:
  postgres:
    env_file: .env
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/

  foundation:
    build: .
    env_file: .env
    image: "${FOUNDATION_IMAGE}"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/foundation:/code/foundation
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - IPYTHONDIR=/code/.ipython

volumes:
  pgdata:
